#!/usr/bin/with-contenv bash
#
# Generates the credentials file for cloudflare
#

CLOUDFLARE_CREDS=/etc/cloudflare/creds.ini

. /etc/simple-logging.sh

loginfo "Setting cloudflare credentials..."
{ [ -z "$CLOUDFLARE_LOGIN" ] || [ -z "$CLOUDFLARE_APIKEY" ]; } && logerror "Cloudflare credentials missing."
mkdir -p "$(dirname $CLOUDFLARE_CREDS)"
cat <<EOF > $CLOUDFLARE_CREDS
dns_cloudflare_email = $CLOUDFLARE_LOGIN
dns_cloudflare_api_key = $CLOUDFLARE_APIKEY
EOF

chmod 600 $CLOUDFLARE_CREDS
chown abc:abc $CLOUDFLARE_CREDS
