#!/usr/bin/with-contenv bash
#
# Generate the initial letsencrypt certificates
#

CONFIG_DIR=/etc/letsencrypt
WORK_DIR=/var/lib/letsencrypt
LOGS_DIR=/var/log/letsencrypt

mkdir -p "$CONFIG_DIR" "$WORK_DIR" "$LOGS_DIR"
chown -R abc:users "$CONFIG_DIR" "$WORK_DIR" "$LOGS_DIR"

s6-envuidgid abc letsencrypt-initial-certificates
